import platform 
x = platform.system() 
print(x) 
print("Platform architecture:", platform.architecture()) 
print('Machine type:', platform.machine()) 
print('System\'s network name:', platform.node()) 
print('Platform information:', platform.platform()) 
print('Platform processor:', platform.platform()) 
print('Operating system:', platform.system()) 
print('System info:', platform.system()) 
print('Python build no. and date:', platform.python_build()) 
print('Python compiler:', platform.python_compiler()) 
print('Python SCM:', platform.python_compiler()) 
print('Python implementation:', platform.python_implementation()) 
print('Python version:', platform.python_version()) 
